# Generated by Django 2.2.10 on 2020-05-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20200512_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='auditors',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
    ]
